<?php
// API key এবং Page Access Token নিরাপদ করার জন্য environment variables ব্যবহার করা হয়েছে
$api_key = getenv('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');
$page_access_token = getenv('EAAHi9dZA2sAcBO6qdVTItKD1XyFsWitRWFTSNI8Cs1IM0GGGbmy0scPKD4TYykmh3nhsjCSbprfw1gOiZAocnaU01ZC8Qo2N1yvsnS0jkOXPVFHAHaVfte19XZCq1kBCCZB3OnTtd3GTfqpEwZBjanZABM9je6JXMranQwTTE2jX9D1ZAXUZB0lOoJeMBhQsiWVs6r6NM8MOOLnYyVm2xuQZDZD');

// ChatGPT API থেকে ডেটা সংগ্রহ
function getChatGPTData($prompt, $api_key) {
    $url = 'https://api.openai.com/v1/chat/completions';

    $data = array(
        'model' => 'gpt-3.5-turbo',
        'messages' => array(
            array('role' => 'user', 'content' => $prompt)
        )
    );

    $options = array(
        'http' => array(
            'header' => "Content-Type: application/json\r\nAuthorization: Bearer $api_key\r\n",
            'method' => 'POST',
            'content' => json_encode($data)
        )
    );

    $context = stream_context_create($options);
    $result = file_get_contents($url, false, $context);

    if ($result === FALSE) {
        return 'Error fetching data from ChatGPT API.';
    }

    return json_decode($result, true);
}

// Facebook API দিয়ে পোস্ট করা
function postToFacebook($message, $page_access_token) {
    $page_id = '109896575144200'; // তোমার পেজ আইডি এখানে বসাও
    $url = "https://graph.facebook.com/$page_id/feed";

    $data = array(
        'message' => $message,
        'access_token' => $page_access_token
    );

    $options = array(
        'http' => array(
            'header' => "Content-Type: application/x-www-form-urlencoded\r\n",
            'method' => 'POST',
            'content' => http_build_query($data)
        )
    );

    $context = stream_context_create($options);
    $result = file_get_contents($url, false, $context);

    if ($result === FALSE) {
        return 'Error posting to Facebook.';
    }

    return json_decode($result, true);
}

// ChatGPT থেকে ডেটা নিয়ে ফেসবুকে পোস্ট করা
$chatgpt_data = getChatGPTData('ফেসবুকের জন্য একটি সেড ক্যাপশন দাও। ', $api_key);

if (isset($chatgpt_data['choices'][0]['message']['content'])) {
    $response = postToFacebook($chatgpt_data['choices'][0]['message']['content'], $page_access_token);

    // ফলাফল চেক করার জন্য লগ রাখা
    file_put_contents('log.txt', print_r($response, true), FILE_APPEND);
} else {
    file_put_contents('log.txt', "Error: No content generated by ChatGPT\n", FILE_APPEND);
}
?>
